### PR TITLE
Add info about deprecation

### PR DESCRIPTION
**Pull request by Jurigag**
https://workivate.atlassian.net/browse/LT-14646s

This one adds info about deprecation

### CODE REVIEW

**Review by 22dr22 — APPROVED** [review]
just readme file changes

**Comment by bluebat-pl** [comment]
Please consider adding deprecated phpDoc tag for each class in this project.

**Review by bluebat-pl — APPROVED** [review]
looks ok, I left one comment

**Comment by Jurigag** [comment]
Added info about deprecated classes.

**Pull request merged**
